"""empty message

Revision ID: 1302dc56e773
Revises: 4cd5d4244bb3
Create Date: 2024-03-26 20:53:37.700954

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1302dc56e773"
down_revision = "4cd5d4244bb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=256), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs")
    # ### end Alembic commands ###
