"""empty message

Revision ID: 227bd30295d1
Revises: e1d7dd2fa00f
Create Date: 2024-04-15 01:36:49.667617

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "227bd30295d1"
down_revision = "e1d7dd2fa00f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_production_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("req_finish_fabrics", sa.Float(), nullable=False),
        sa.Column("fabric_allowance", sa.Float(), nullable=False),
        sa.Column("rec_beam_length_yds", sa.Float(), nullable=False),
        sa.Column("shrink_allow", sa.Float(), nullable=False),
        sa.Column("req_grey_fabric", sa.Float(), nullable=False),
        sa.Column("req_beam_length_yds", sa.Float(), nullable=False),
        sa.Column("total_pdn_yds", sa.Float(), nullable=False),
        sa.Column("warp_count", sa.Float(), nullable=False),
        sa.Column("weft_count", sa.Float(), nullable=False),
        sa.Column("epi", sa.Integer(), nullable=False),
        sa.Column("ppi", sa.Integer(), nullable=False),
        sa.Column("rejection", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "production_report",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("req_finish_fabrics", sa.Float(), nullable=False),
        sa.Column("fabric_allowance", sa.Float(), nullable=False),
        sa.Column("rec_beam_length_yds", sa.Float(), nullable=False),
        sa.Column("shrink_allow", sa.Float(), nullable=False),
        sa.Column("req_grey_fabric", sa.Float(), nullable=False),
        sa.Column("req_beam_length_yds", sa.Float(), nullable=False),
        sa.Column("total_pdn_yds", sa.Float(), nullable=False),
        sa.Column("warp_count", sa.Float(), nullable=False),
        sa.Column("weft_count", sa.Float(), nullable=False),
        sa.Column("epi", sa.Integer(), nullable=False),
        sa.Column("ppi", sa.Integer(), nullable=False),
        sa.Column("rejection", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("production_report")
    op.drop_table("processed_production_data")
    # ### end Alembic commands ###
